name: ci

on: [push, workflow_dispatch]

jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up dependencies
        run: npm install
      - name: Build website
        run: npm run build
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
